---

# 31.6. Bridging
# https://www.freebsd.org/doc/handbook/network-bridging.html

# TODO: Enable monitoring
# 31.6.4. SNMP Monitoring

- name: "bridge: Configure bridges in /etc/rc.conf"
  lineinfile:
    state: "{{ item.state }}"
    dest: "/etc/rc.conf"
    regexp: "^ifconfig_{{ item.bridge }}"
    line: "ifconfig_{{ item.bridge }}=\"{{ item.options }}\""
    backup: "{{ fn_backup_conf }}"
  loop: "{{ fn_bridges }}"
  notify: restart netif

- name: "bridge: Create list of cloned_interfaces"
  set_fact:
    fn_cloned_interfaces: "{{ fn_cloned_interfaces }} + ' ' + {{ item.bridge }}"
  loop: "{{ fn_bridges }}"
  when: item.state == "present"

- name: "bridge: Configure cloned_interfaces in /etc/rc.conf"
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "^cloned_interfaces"
    line: "cloned_interfaces=\"{{ fn_cloned_interfaces }}\""
    backup: "{{ fn_backup_conf }}"
  when: fn_cloned_interfaces|length > 0
  notify: netif cloneup

- name: "bridge: Remove cloned_interfaces from /etc/rc.conf"
  lineinfile:
    state: absent
    dest: "/etc/rc.conf"
    regexp: "^cloned_interfaces"
    backup: "{{ fn_backup_conf }}"
  when: fn_cloned_interfaces|length == 0
  notify: restart netif

# EOF
...
