---

# 31.6. Bridging
# https://www.freebsd.org/doc/handbook/network-bridging.html
# 31.7. Link Aggregation and Failover
# https://www.freebsd.org/doc/handbook/network-aggregation.html
# 31.10. Common Address Redundancy Protocol (CARP)
# https://www.freebsd.org/doc/handbook/carp.html
# 14.6. Managing Jails with ezjail
# https://www.freebsd.org/doc/handbook/jails-ezjail.html

- name: "cloned-interfaces: Debug fn_cloned_interfaces_list"
  ansible.builtin.debug:
    msg: "{{ fn_cloned_interfaces_list }}"
  when: fn_debug|bool

- name: "cloned-interfaces: Configure cloned_interfaces in /etc/rc.conf"
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    regexp: '^\s*cloned_interfaces\s*=(.*)$'
    line: 'cloned_interfaces="{{ fn_cloned_interfaces_list }}"'
    backup: "{{ fn_backup_conf }}"
  notify: cloneup netif
  when: fn_cloned_interfaces_list|length > 0

- name: "cloned-interfaces: Remove cloned_interfaces from /etc/rc.conf"
  ansible.builtin.replace:
    dest: /etc/rc.conf
    regexp: '^\s*cloned_interfaces(.*)$'
    backup: "{{ fn_backup_conf }}"
  notify: cloneup netif
  when: fn_cloned_interfaces_list|length == 0

- name: "cloned-interfaces: Configure interfaces create_args in /etc/rc.conf"
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    state: "{{ item.state|default('present') }}"
    regexp: '^\s*create_args_{{ item.interface }}\s*=(.*)$'
    line: 'create_args_{{ item.interface }}="{{ item.create }}"'
    backup: "{{ fn_backup_conf }}"
  loop: "{{ fn_cloned_interfaces }}"
  notify: restart netif
  when: item.create is defined

- name: "cloned-interfaces: Configure interfaces options in /etc/rc.conf"
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    state: "{{ item.state|default('present') }}"
    regexp: '^\s*ifconfig_{{ item.interface }}\s*=(.*)$'
    line: 'ifconfig_{{ item.interface }}="{{ item.options }}"'
    backup: "{{ fn_backup_conf }}"
  loop: "{{ fn_cloned_interfaces }}"
  notify: restart netif
  when: item.options is defined

# EOF
...
