---

- name: "FreeBSD Network Debug"
  vars:
    msg: |
         ansible_architecture [ {{ ansible_architecture }} ]
         ansible_os_family [ {{ ansible_os_family }} ]
         ansible_distribution [ {{ ansible_distribution }} ]
         ansible_distribution_major_version [ {{ ansible_distribution_major_version }} ]
         ansible_distribution_version [ {{ ansible_distribution_version }} ]
         ansible_distribution_release [ {{ ansible_distribution_release }} ]

         fn_backup_conf [ {{ fn_backup_conf }} ]
         fn_wlans
           {{ fn_wlans | to_yaml }}
         fn_interfaces
           {{ fn_interfaces | to_yaml }}
         fn_aliases
           {{ fn_aliases | to_yaml }}
         fn_defaultrouter [ {{ fn_defaultrouter }} ]
         fn_nameserver [ {{ fn_nameserver }} ]
         fn_gateway_enable [ {{ fn_gateway_enable }} ]
         fn_static_routes_list [ {{ fn_static_routes_list }} ]
         fn_static_routes
           {{ fn_static_routes | to_yaml }}
         fn_cloned_interfaces [ {{ fn_cloned_interfaces }} ]
         fn_bridges
           {{ fn_bridges | to_yaml }}
         fn_laggs
           {{ fn_laggs | to_yaml }}

  debug:
    msg: "{{ msg.split('\n') }}"

# EOF
...
