---

- name: "Interfaces: Configure wlans in /etc/rc.conf"
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    state: "{{ item.state | d('present') }}"
    regexp: ^\s*wlans_{{ item.device }}\s*=(.*)$
    line: wlans_{{ item.device }}="{{ item.interface }}"
    backup: "{{ fn_backup_conf }}"
  loop: "{{ fn_wlans }}"
  notify: restart netif

- name: "Interfaces: Configure interfaces create_args in /etc/rc.conf"
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    state: "{{ item.state | d('present') }}"
    regexp: ^\s*create_args_{{ item.interface }}\s*=(.*)$
    line: create_args_{{ item.interface }}="{{ item.create }}"
    backup: "{{ fn_backup_conf }}"
  loop: "{{ fn_interfaces | selectattr('create', 'defined') }}"
  notify: restart netif

- name: "Interfaces: Configure interfaces options in /etc/rc.conf"
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    state: "{{ item.state | d('present') }}"
    regexp: ^\s*ifconfig_{{ item.interface }}\s*=(.*)$
    line: ifconfig_{{ item.interface }}="{{ item.options }}"
    backup: "{{ fn_backup_conf }}"
  loop: "{{ fn_interfaces | selectattr('options', 'defined') }}"
  notify: restart netif

- name: "Interfaces: Configure interface aliases in /etc/rc.conf"
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    state: "{{ item.1.state | d('present') }}"
    regexp: ^\s*ifconfig_{{ item.0.interface }}_{{ item.1.alias }}\s*=(.*)$
    line: ifconfig_{{ item.0.interface }}_{{ item.1.alias }}="{{ item.1.options }}"
    backup: "{{ fn_backup_conf }}"
  loop: "{{ fn_aliases | subelements('aliases') }}"
  loop_control:
    label: "{{ item.0.interface }} {{ item.1.alias }} {{ item.1.options }}"
  notify: restart netif

# EOF
