---

# 31.7. Link Aggregation and Failover
# https://www.freebsd.org/doc/handbook/network-aggregation.html

- name: "lagg: Configure laggs in /etc/rc.conf"
  lineinfile:
    state: "{{ item.state }}"
    dest: "/etc/rc.conf"
    regexp: "^ifconfig_{{ item.lagg }}"
    line: "ifconfig_{{ item.lagg }}=\"{{ item.options }}\""
    backup: "{{ fn_backup_conf }}"
  loop: "{{ fn_laggs }}"
  notify: restart netif

- name: "lagg: Create list of cloned_interfaces"
  set_fact:
    fn_cloned_interfaces: "{{ fn_cloned_interfaces }} + ' ' + {{ item.lagg }}"
  loop: "{{ fn_laggs }}"
  when: item.state == "present"

- name: "lagg: Configure cloned_interfaces in /etc/rc.conf"
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "^cloned_interfaces"
    line: "cloned_interfaces=\"{{ fn_cloned_interfaces }}\""
    backup: "{{ fn_backup_conf }}"
  when: fn_cloned_interfaces|length > 0
  notify: restart netif

- name: "lagg: Remove cloned_interfaces from /etc/rc.conf"
  lineinfile:
    state: absent
    dest: "/etc/rc.conf"
    regexp: "^cloned_interfaces"
    backup: "{{ fn_backup_conf }}"
  when: fn_cloned_interfaces|length == 0
  notify: restart netif

# EOF
...
