---
# tasks for freebsd_network

- name: Import debug.yml
  ansible.builtin.import_tasks: debug.yml
  when: fn_debug | bool
  tags: fn_debug

- name: Import interfaces.yml
  ansible.builtin.import_tasks: interfaces.yml
  tags: fn_interfaces

- name: Import cloned-interfaces.yml
  ansible.builtin.import_tasks: cloned-interfaces.yml
  tags: fn_cloned_interfaces

# - ansible.builtin.import_tasks: vlans.yml
#   tags: fn_vlans

# - ansible.builtin.import_tasks: ipv6.yml
#   tags: fn_ipv6

- name: Import router.yml
  ansible.builtin.import_tasks: router.yml
  tags: fn_router

# EOF
