---
# tasks for freebsd_network

- import_tasks: debug.yml
  when: fn_debug
  tags: [fn_debug, always]

- import_tasks: interfaces.yml
  tags: fn_interfaces

- import_tasks: cloned-interfaces.yml
  tags: fn_cloned_interfaces

#- import_tasks: vlans.yml
#  tags: fn_vlans

#- import_tasks: ipv6.yml
#  tags: fn_ipv6

- import_tasks: router.yml
  tags: fn_router

# EOF
...
