---
# handlers for freebsd_network

- name: restart netif
  ansible.builtin.service:
    name: netif
    state: restarted

- name: restart routing
  ansible.builtin.service:
    name: routing
    state: restarted

- name: cloneup netif
  command:
    cmd: /etc/rc.d/netif cloneup

# EOF
...
