---
# handlers for freebsd_network

- name: restart netif
  service:
    name: netif
    state: restarted

- name: restart routing
  service:
    name: routing
    state: restarted

- name: netif cloneup
  command: "/etc/rc.d/netif cloneup"

# EOF
...
